### ISSUE TITLE
Treepublisher can error with array dereference of undef

### ISSUE THREAD

**Issue by kjsanger** [wtsi-npg/npg_irods#286]
`Can't use an undefined value as an ARRAY reference at /software/npg/20200825/bin/../lib/perl5/WTSI/NPG/iRODS/BatonClient.pm line 878.`

Example failed jobs 34874-archive_pp_data_to_irods[1#285] and 34874-archive_pp_data_to_irods[1#351].

Possibly because there are no files to archive?

**Comment by mgcam** [comment]
Most likely this was because there were no files to archive. Since at the time of creating a job we do not know whether there are going to be any files, we need the code to log 'Nothing to do' and exit normally.

**Comment by kjsanger** [comment]
Unable to reproduce so far.

**Comment by kjsanger** [comment]
Caused by https://github.com/wtsi-npg/perl-irods-wrap/issues/208

**Comment by kjsanger** [comment]
Fixed by https://github.com/wtsi-npg/perl-irods-wrap/pull/211
