### ISSUE TITLE
add --id_run as a option to npg_publish_illumina_run.pl

### ISSUE THREAD

**Issue by srl147** [wtsi-npg/npg_irods#46]
npg_publish_illumina_run.pl doesn't has a --id_run option. The runfolder name for the HiSeq 4000 test run (19844) doesn't include the id_run so I tried to specify it on the command line. The log loader script already supports this. Longer term we might move to using the default Illumina runfolder names and linking to a run id via the tracking database

**Comment by keithj** [comment]
Fixed by #51
